version: '3'
services:
  phpmyadmin:
    restart: always
    image: nazarpc/phpmyadmin
    environment:
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_MAIL}
    volumes:
      - ${CONFIG_PATH}:/var/www/html/config.inc.php
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
