version: '2'
services:
  phpmyadmin:
    restart: always
    image: nazarpc/phpmyadmin
    environment:
      VIRTUAL_HOST: db.example.com
      VIRTUAL_PORT: 80
      MYSQL_HOST: db:3306
      LETSENCRYPT_HOST: db.example.com
      LETSENCRYPT_EMAIL: info@db.example.com
    volumes:
      - ./conf/config.inc.php:/var/www/html/config.inc.php
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
